# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0015_auto_20160421_0000'),
        ('filer', '0004_auto_20160328_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMedia',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('height', models.CharField(default='100%', help_text='height in pixels or %', max_length=10, verbose_name='container height')),
                ('add_style', models.BooleanField(default=True, help_text='link default style sheet', verbose_name='add style')),
                ('overlay', models.CharField(blank=True, help_text='to add a css overlay enter the colour of the overlay, e.g. rgba(0,0,0,0.7)', max_length=25, null=True, verbose_name='overlay')),
                ('image_position', models.CharField(default='center center', help_text='the css position of the image', max_length=50, verbose_name='image position')),
                ('video_mp4', models.FileField(blank=True, help_text='Video in the mp4 format', null=True, upload_to='videos/djangocms_bg_media', verbose_name='video mp4')),
                ('video_ogv', models.FileField(blank=True, help_text='Video in the ogv format', null=True, upload_to='videos/djangocms_bg_media', verbose_name='video ogv')),
                ('video_webm', models.FileField(blank=True, help_text='Video in the webm format', null=True, upload_to='videos/djangocms_bg_media', verbose_name='video ogv')),
                ('vide_json_config', models.TextField(blank=True, help_text='the optional json object for the vide config. Click <a href="https://github.com/VodkaBears/Vide" target="_blank"> here</a> for more info', null=True, verbose_name='vide js json config')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='filer.Image', verbose_name='image')),
                ('video_poster', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='video poster')),
            ],
            options={
                'verbose_name': 'Background Media',
                'verbose_name_plural': 'Background Media',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
